### ISSUE TITLE
对现有功能/界面的建议和希望增加的新功能

### ISSUE THREAD

**Issue by lsbnbdz** [Chenlvin/CloudMusic-HarmonyOSNext#2]
非常开心能使用您开发的替代网易云音乐的APP，我想提几点建议，旨在在完成基础功能下能有更好的体验，

- **改进建议**

1. 扫码登陆界面可以自动获取登陆状态
2. 歌曲搜索只有30首歌，希望可以获取更多
3. 主页右上角`正在播放`的音符符号希望可以改成底部常驻的音乐播放控件包含`上一首`，`下一首`，`播放/暂停`，`播放进度条`，`播放列表（此处弹出播放列表界面）`，`播放模式（随机，顺序，循环，列表）`，`封面展示`，`歌曲名`，`演唱者`
4. 歌单界面嘴上出空白位置，不要音符符号，改成`XXX的歌单/XXX的音乐/XXX的乐库`等都可以，再加一个头像宿略图，位置可酌情扩大

- **新的功能**

1. 在歌单列表点击歌曲可以直接播放，底部常驻播放控件更新状态
2. 在改进建议中提到的播控组件可以正常工作，例如歌曲上/下一首切换，暂停歌曲，显示基础信息等
3. 新增正在播放列表界面，列表展示`歌曲封面`，`歌曲名称`，`演唱者`，并可以点击播放歌曲
5. 歌单可以`新增/删除歌曲`，可以单首操作/批量操作
6. 搜索获取到歌曲界面，点击可以听歌，`长按/左滑`可以展示`收藏到歌单`，`添加到下一首`
7. 新增歌词展示界面，支持点击/拖动歌词调整进度
8. 下载歌曲支持批量缓存到应用（下载到手机文件夹还要一个一个点，这个没办法，华为没给权限）
9. 支持歌单搜索，`收藏/取消收藏`歌单
10. 增加今日推荐，替换位置为原来`正在播放歌曲`位置，感觉正好

以上建议可在有最少功能下有最完整的体验，其他花里胡哨的功能就不要了，如能采纳，三生有幸，不胜感激。

**Comment by Chenlvin** [comment]
谢谢你的建议！你的建议非常详细，也很有帮助
现已将部分功能纳入开发计划，并将在接下来的版本逐步实现
但由于时间和精力问题，部分功能开发周期较长，希望能够理解

**Comment by lsbnbdz** [comment]
> 谢谢你的建议！你的建议非常详细，也很有帮助 现已将部分功能纳入开发计划，并将在接下来的版本逐步实现 但由于时间和精力问题，部分功能开发周期较长，希望能够理解

非常感谢作者能将我的部分建议纳入后续的开发计划，现将我使用`0.9.8`和`0.9.9`版本的感受反馈给作者。总体来说作为网易云的替代品只用来听歌除了歌词功能，其他已经完全达标了，下面希望可以优化这些细节（希望作者不要打乱自己已有的开发计划，如采纳部分细节优化，也请安排至已有计划之后）：
- 底部播控组件每次打开都是空白的，无记忆上次播放的歌曲，而且在无歌曲的情况下`播放/暂停`仍可以点击
![image](https://github.com/user-attachments/assets/e6763238-3f7e-43fe-850d-eedf10c07db5)

- 搜索框的样式与整个播放器布局样式不搭，不够沉浸（颜色与背景更统一），搜索按钮与搜索按钮可以更紧密，可以参考华为音乐的实现，还有具体的放置位置，作者可以自己酌情考虑
![98e25ec3e4368300e2428f9bb888f07](https://github.com/user-attachments/assets/f42b9b13-5070-4956-b23e-e9dbc3083d64)
如有余力可继续完成点击搜索框后跳转新界面，搜索框下有搜索历史，再下面的热门推荐就可有可无了
![02b749d3c9be005113b788e84cd9abf](https://github.com/user-attachments/assets/8340d79d-1236-4885-a0cc-b686ff3d4085)
- 希望在点击歌单的某个歌曲后，可以把整个歌单都加入到播放列表，更符合播放逻辑

祝作者健康顺遂，百事无忧~
